image: docker:latest 
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - package

docker-build:
  stage: package
  script:
    - docker build -t registry.thestorm.com.br/strm/apache .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.thestorm.com.br
    - docker push registry.thestorm.com.br/strm/apache

